import {CreateEventInputType, EventPrivacySetting, EventStatus} from '@/graphql/types';

const events: CreateEventInputType[] = [
    {
        title: 'Rocking The Daisies 2024',
        description: 'Rocking The Daisies 2024',
        startDateTime: '2024-06-26',
        endDateTime: '2024-06-26',
        location: 'Cape Town, Winefarm, 8000',
        organizerList: ['user002', 'host001'],
        eventCategoryList: [],
        capacity: 4500,
        rSVPList: [],
        tags: {
            stages: {
                stage1: 'Savanna',
                stage2: 'Heineken',
                stage3: 'Jack Daniels',
            },
            camps: {
                camp1: 'Priority',
                camp2: 'Higher Priority',
            },
        },
        status: EventStatus.Ongoing,
        media: {
            featuredImageUrl: 'https://random.imagecdn.app/500/500',
            otherMediaData: {},
        },
        additionalDetails: {},
        comments: {},
        privacySetting: EventPrivacySetting.Public,
    },
    {
        title: 'Rocking The Daisies 2023',
        description: 'Rocking The Daisies 2023',
        startDateTime: '2024-06-02',
        endDateTime: '2024-06-03',
        location: 'Cape Town, Stellenbosch, 8000',
        organizerList: ['user001', 'host002'],
        eventCategoryList: [],
        capacity: 5000,
        rSVPList: [],
        tags: {
            stages: {
                stage1: 'Savanna',
                stage2: 'Heineken',
                stage3: 'Jack Daniels',
            },
            camps: {
                camp1: 'Priority',
                camp2: 'Higher Priority',
            },
        },
        status: EventStatus.Completed,
        media: {
            featuredImageUrl: 'https://random.imagecdn.app/400/400',
            otherMediaData: {},
        },
        additionalDetails: {},
        comments: {},
        privacySetting: EventPrivacySetting.Public,
    },
    {
        title: 'coachella 2023',
        description: 'coachella 2023',
        startDateTime: '2024-12-26',
        endDateTime: '2024-12-26',
        location: 'Cape Town, Stellenbosch, 8000',
        organizerList: ['user001', 'host002'],
        eventCategoryList: [],
        capacity: 1000,
        rSVPList: [],
        tags: {
            stages: {
                stage1: 'Savanna',
                stage2: 'Heineken',
                stage3: 'Jack Daniels',
            },
            camps: {
                camp1: 'Priority',
                camp2: 'Higher Priority',
            },
        },
        status: EventStatus.Completed,
        media: {
            featuredImageUrl: 'https://random.imagecdn.app/550/550',
            otherMediaData: {},
        },
        additionalDetails: {},
        comments: {},
        privacySetting: EventPrivacySetting.Public,
    },
    {
        title: 'Durban July 2023',
        description: 'Durban July 2023',
        startDateTime: '2024-08-16',
        endDateTime: '2024-08-16',
        location: 'KZN, Durban, 8000',
        organizerList: [],
        eventCategoryList: [],
        capacity: 10000,
        rSVPList: [],
        status: EventStatus.Upcoming,
        media: {
            featuredImageUrl: 'https://random.imagecdn.app/500/550',
            otherMediaData: {},
        },
        additionalDetails: {},
        comments: {},
        privacySetting: EventPrivacySetting.Public,
    },
    {
        title: 'Four Oceans Marathon 2023',
        description: 'Four Oceans Marathon 2023',
        startDateTime: '2024-09-13',
        endDateTime: '2024-09-13',
        location: 'Cape Town, Winefarm, 8000',
        organizerList: ['user002', 'host001'],
        eventCategoryList: [],
        capacity: 200,
        rSVPList: [],
        tags: {},
        status: EventStatus.Completed,
        media: {
            featuredImageUrl: 'https://picsum.photos/400',
            otherMediaData: {},
        },
        additionalDetails: {},
        comments: {},
        privacySetting: EventPrivacySetting.Public,
    },
    {
        title: 'The Ring Reloaded Fight Night 2023',
        description: 'The Ring Reloaded Fight Night 2023',
        startDateTime: '2024-09-13',
        endDateTime: '2024-09-16',
        location: 'Cape Town, Winefarm, 8000',
        organizerList: ['user002', 'host001'],
        eventCategoryList: [],
        capacity: 150,
        rSVPList: [],
        tags: {},
        status: EventStatus.Completed,
        media: {
            featuredImageUrl: 'https://picsum.photos/300',
            otherMediaData: {},
        },
        additionalDetails: {},
        comments: {},
        privacySetting: EventPrivacySetting.Public,
    },
    {
        title: 'Fear Factor 2023',
        description: 'Fear Factor 2023',
        startDateTime: '2024-09-13',
        endDateTime: '2024-09-14',
        location: 'Cape Town, Winefarm, 8000',
        organizerList: [],
        eventCategoryList: [],
        capacity: 80,
        rSVPList: ['user001', 'user002', 'user003'],
        tags: {},
        status: EventStatus.Completed,
        media: {
            featuredImageUrl: 'https://picsum.photos/200',
            otherMediaData: {},
        },
        additionalDetails: {},
        comments: {},
        privacySetting: EventPrivacySetting.Public,
    },
];

export default events;
