import {Gender, CreateUserInputType} from '@/graphql/types';

const users: CreateUserInputType[] = [
    {
        // id: 'user001',
        email: 'user001@gmail.com',
        username: 'jackBaur',
        address: 'KZN, Durban, 8000',
        birthdate: '1994-06-26',
        family_name: 'Baur',
        gender: Gender.Male,
        given_name: 'Jack',
        password: 'dfuyihjknbsndhj',
        phone_number: '+12345678990',
        profile_picture: '',
    },
    {
        // id: 'host001',
        email: 'jay@rocknation.com',
        username: 'jayz',
        address: 'USA, Brooklyn, 8000',
        birthdate: '1990-01-21',
        family_name: 'Carter',
        gender: Gender.Male,
        given_name: 'Sean',
        password: 'tryuik',
        phone_number: '+12345678990',
        profile_picture: '',
    },
    {
        // id: 'user002',
        email: 'celin@yahoo.com',
        username: 'celin352',
        address: 'WC, Parklands, 8000',
        birthdate: '1999-06-25',
        family_name: 'Maluleke',
        gender: Gender.Female,
        given_name: 'Celin',
        password: 'wreiujk22',
        phone_number: '+12345678990',
        profile_picture: '',
    },
    {
        // id: 'host002',
        email: 'Jeff@amazon.com',
        username: 'jeffbez',
        address: 'USA, Seattle, 8000',
        birthdate: '1997-07-05',
        family_name: 'Bezos',
        gender: Gender.Male,
        given_name: 'Jeff',
        password: '123456789',
        phone_number: '+12345678990',
        profile_picture: '',
    },
];

export default users;
