import {CreateEventInputType} from '@ntlango/commons/types';
import {EventPrivacySetting, EventStatus} from '@ntlango/commons/types/event';

const events: CreateEventInputType[] = [
  {
    title: 'Rocking The Daisies 2024',
    description: 'Rocking The Daisies 2024',
    location: {
      locationType: 'venue',
      address: {
        street: 'Winefarm',
        city: 'Cape Town',
        state: 'Western Cape',
        zipCode: '8000',
        country: 'South Africa',
      },
    },
    recurrenceRule: 'FREQ=YEARLY;BYMONTH=6;BYMONTHDAY=26',
    organizerList: ['user002', 'host001'],
    eventCategoryList: [],
    capacity: 4500,
    rSVPList: [],
    tags: {
      stages: {
        stage1: 'Savanna',
        stage2: 'Heineken',
        stage3: 'Jack Daniels',
      },
      camps: {
        camp1: 'Priority',
        camp2: 'Higher Priority',
      },
    },
    status: EventStatus.Ongoing,
    media: {
      featuredImageUrl: 'https://random.imagecdn.app/500/500',
      otherMediaData: {},
    },
    additionalDetails: {},
    comments: {},
    privacySetting: EventPrivacySetting.Public,
  },
  {
    title: 'Rocking The Daisies 2023',
    description: 'Rocking The Daisies 2023',
    location: {
      locationType: 'venue',
      address: {
        street: 'Stellenbosch',
        city: 'Cape Town',
        state: 'Western Cape',
        zipCode: '8000',
        country: 'South Africa',
      },
    },
    recurrenceRule: 'FREQ=YEARLY;BYMONTH=6;BYMONTHDAY=2,3',
    organizerList: ['user001', 'host002'],
    eventCategoryList: [],
    capacity: 5000,
    rSVPList: [],
    tags: {
      stages: {
        stage1: 'Savanna',
        stage2: 'Heineken',
        stage3: 'Jack Daniels',
      },
      camps: {
        camp1: 'Priority',
        camp2: 'Higher Priority',
      },
    },
    status: EventStatus.Completed,
    media: {
      featuredImageUrl: 'https://random.imagecdn.app/400/400',
      otherMediaData: {},
    },
    additionalDetails: {},
    comments: {},
    privacySetting: EventPrivacySetting.Public,
  },
  {
    title: 'coachella 2023',
    description: 'coachella 2023',
    location: {
      locationType: 'venue',
      address: {
        street: 'Stellenbosch',
        city: 'Cape Town',
        state: 'Western Cape',
        zipCode: '8000',
        country: 'South Africa',
      },
    },
    recurrenceRule: 'FREQ=YEARLY;BYMONTH=12;BYMONTHDAY=26',
    organizerList: ['user001', 'host002'],
    eventCategoryList: [],
    capacity: 1000,
    rSVPList: [],
    tags: {
      stages: {
        stage1: 'Savanna',
        stage2: 'Heineken',
        stage3: 'Jack Daniels',
      },
      camps: {
        camp1: 'Priority',
        camp2: 'Higher Priority',
      },
    },
    status: EventStatus.Completed,
    media: {
      featuredImageUrl: 'https://random.imagecdn.app/550/550',
      otherMediaData: {},
    },
    additionalDetails: {},
    comments: {},
    privacySetting: EventPrivacySetting.Public,
  },
  {
    title: 'Durban July 2023',
    description: 'Durban July 2023',
    location: {
      locationType: 'venue',
      address: {
        street: '',
        city: 'Durban',
        state: 'KZN',
        zipCode: '8000',
        country: 'South Africa',
      },
    },
    recurrenceRule: 'FREQ=YEARLY;BYMONTH=8;BYMONTHDAY=16',
    organizerList: [],
    eventCategoryList: [],
    capacity: 10000,
    rSVPList: [],
    status: EventStatus.Upcoming,
    media: {
      featuredImageUrl: 'https://random.imagecdn.app/500/550',
      otherMediaData: {},
    },
    additionalDetails: {},
    comments: {},
    privacySetting: EventPrivacySetting.Public,
  },
  {
    title: 'Four Oceans Marathon 2023',
    description: 'Four Oceans Marathon 2023',
    location: {
      locationType: 'venue',
      address: {
        street: 'Winefarm',
        city: 'Cape Town',
        state: 'Western Cape',
        zipCode: '8000',
        country: 'South Africa',
      },
    },
    recurrenceRule: 'FREQ=YEARLY;BYMONTH=8;BYMONTHDAY=16',
    organizerList: ['user002', 'host001'],
    eventCategoryList: [],
    capacity: 200,
    rSVPList: [],
    tags: {},
    status: EventStatus.Completed,
    media: {
      featuredImageUrl: 'https://picsum.photos/400',
      otherMediaData: {},
    },
    additionalDetails: {},
    comments: {},
    privacySetting: EventPrivacySetting.Public,
  },
  {
    title: 'The Ring Reloaded Fitness Bootcamp 2023',
    description: 'The Ring Reloaded Fitness Bootcamp 2023',
    location: {
      locationType: 'online',
    },
    recurrenceRule: 'FREQ=YEARLY;BYMONTH=9;BYMONTHDAY=13',
    organizerList: ['user002', 'host001'],
    eventCategoryList: [],
    capacity: 150,
    rSVPList: [],
    tags: {},
    status: EventStatus.Completed,
    media: {
      featuredImageUrl: 'https://picsum.photos/300',
      otherMediaData: {},
    },
    additionalDetails: {},
    comments: {},
    privacySetting: EventPrivacySetting.Public,
  },
  {
    title: 'Fear Factor 2023',
    description: 'Fear Factor 2023',
    location: {
      locationType: 'tba',
      details: 'We will let you know as soon as we know',
    },
    recurrenceRule: 'FREQ=YEARLY;BYMONTH=8;BYMONTHDAY=16',
    organizerList: [],
    eventCategoryList: [],
    capacity: 80,
    rSVPList: ['user001', 'user002', 'user003'],
    tags: {},
    status: EventStatus.Completed,
    media: {
      featuredImageUrl: 'https://picsum.photos/200',
      otherMediaData: {},
    },
    additionalDetails: {},
    comments: {},
    privacySetting: EventPrivacySetting.Public,
  },
];

export default events;
