import type {CreateEventInput} from '@ntlango/commons/types';
import {EventLifecycleStatus, EventPrivacySetting, EventStatus, EventVisibility} from '@ntlango/commons/types/event';

export type EventSeedData = CreateEventInput & {
  orgIndex?: number;
  venueIndex?: number;
};

const events: EventSeedData[] = [
  {
    title: 'Signal Studios Urban Maker Fair',
    summary: 'Experience design, art, and tech installations across two floors.',
    description:
      'A weekend of interactive installations, generative art, and hardware showcase by emerging creatives.',
    location: {
      locationType: 'venue',
      address: {
        street: '120 Exchange Rd',
        city: 'Durban',
        state: 'KwaZulu-Natal',
        zipCode: '4001',
        country: 'South Africa',
      },
    },
    recurrenceRule: 'FREQ=YEARLY;BYMONTH=9;BYMONTHDAY=12,13',
    organizerList: [],
    eventCategoryList: [],
    capacity: 600,
    tags: {features: ['installations', 'workshops'], vibe: ['creative', 'immersive']},
    status: EventStatus.Upcoming,
    lifecycleStatus: EventLifecycleStatus.Published,
    visibility: EventVisibility.Public,
    media: {
      featuredImageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80',
      otherMediaData: {},
    },
    heroImage: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=80',
    additionalDetails: {floorPlan: 'Main + Studio 2'},
    comments: {},
    privacySetting: EventPrivacySetting.Public,
    orgIndex: 0,
    venueIndex: 0,
  },
  {
    title: 'Harbour Collective: Salt City Night Market',
    summary: 'Food, craft, and jazz curated by coastal makers.',
    description:
      'Monthly showcase of small-batch food, craft cocktails, live jazz, and a rotating vinyl guest DJ.',
    location: {
      locationType: 'venue',
      address: {
        street: 'Pier 7 Promenade',
        city: 'Cape Town',
        state: 'Western Cape',
        zipCode: '8001',
        country: 'South Africa',
      },
    },
    recurrenceRule: 'FREQ=MONTHLY;BYDAY=FR;INTERVAL=1',
    organizerList: [],
    eventCategoryList: [],
    capacity: 900,
    tags: {themes: ['music', 'food', 'nightlife']},
    status: EventStatus.Ongoing,
    lifecycleStatus: EventLifecycleStatus.Published,
    visibility: EventVisibility.Public,
    media: {
      featuredImageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
      otherMediaData: {},
    },
    heroImage: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=80',
    additionalDetails: {featuredChef: 'Mandla Okafor', afterparty: 'Harbour Rooftop'},
    comments: {},
    privacySetting: EventPrivacySetting.Public,
    orgIndex: 1,
    venueIndex: 1,
  },
  {
    title: 'Harbour Collective Rooftop Afterparty',
    summary: 'Invite-only rooftop set for Harbour Collective members.',
    description:
      'A clandestine rooftop session with voltaic sets, immersive visuals, and late-night street food.',
    location: {
      locationType: 'venue',
      address: {
        street: '11 Woolworths Lane',
        city: 'Cape Town',
        state: 'Western Cape',
        zipCode: '8002',
        country: 'South Africa',
      },
    },
    recurrenceRule: 'FREQ=QUARTERLY;BYDAY=SA',
    organizerList: [],
    eventCategoryList: [],
    capacity: 220,
    tags: {access: ['invite-only'], music: ['amapiano', 'house']},
    status: EventStatus.Upcoming,
    lifecycleStatus: EventLifecycleStatus.Draft,
    visibility: EventVisibility.Private,
    media: {
      featuredImageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80',
      otherMediaData: {},
    },
    heroImage: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=80',
    additionalDetails: {hostedBy: 'Harbour Collective Membership'},
    comments: {},
    privacySetting: EventPrivacySetting.Private,
    orgIndex: 1,
    venueIndex: 1,
  },
  {
    title: 'Emergent Labs: Innovation Summit',
    summary: 'Hybrid summit for AI, climate, and cultural founders.',
    description:
      'Two-day salon of talks, hands-on labs, and guided networking for future-focused founders.',
    location: {
      locationType: 'virtual',
      details: 'Private stream link shared 48h before start',
    },
    recurrenceRule: 'FREQ=ANNUAL;BYMONTH=11;BYMONTHDAY=18,19',
    organizerList: [],
    eventCategoryList: [],
    capacity: 180,
    tags: {tracks: ['AI', 'Climate'], format: ['hybrid']},
    status: EventStatus.Upcoming,
    lifecycleStatus: EventLifecycleStatus.Published,
    visibility: EventVisibility.Unlisted,
    media: {
      featuredImageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80',
      otherMediaData: {},
    },
    heroImage: 'https://images.unsplash.com/photo-1474631245212-32dc3c8310c6?auto=format&fit=crop&w=1600&q=80',
    additionalDetails: {featuredSpeakers: ['Nia Dlamini', 'Marcelo Adeyemi']},
    comments: {},
    privacySetting: EventPrivacySetting.Private,
    orgIndex: 2,
    venueIndex: 2,
  },
  {
    title: 'Emergent Labs Founders Studio Day',
    summary: 'Small-group working session with coaches and creative technologists.',
    description:
      'Hands-on studio day with breakout coaching, rapid prototyping kits, and mentorship pods.',
    location: {
      locationType: 'venue',
      address: {
        street: '301 Gallery Way',
        city: 'Johannesburg',
        state: 'Gauteng',
        zipCode: '2092',
        country: 'South Africa',
      },
    },
    recurrenceRule: 'FREQ=MONTHLY;BYMONTHDAY=3',
    organizerList: [],
    eventCategoryList: [],
    capacity: 40,
    tags: {format: ['workshop', 'studio'], mood: ['intimate']},
    status: EventStatus.Ongoing,
    lifecycleStatus: EventLifecycleStatus.Published,
    visibility: EventVisibility.Invitation,
    media: {
      featuredImageUrl: 'https://images.unsplash.com/photo-1474631245212-32dc3c8310c6?auto=format&fit=crop&w=1200&q=80',
      otherMediaData: {},
    },
    heroImage: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=80',
    additionalDetails: {kit: 'Rapid Prototype Pack'},
    comments: {},
    privacySetting: EventPrivacySetting.Private,
    orgIndex: 2,
    venueIndex: 2,
  },
  {
    title: 'Cape Town Wellness Immersion',
    summary: 'Three-day wellness retreat beside the ocean.',
    description:
      'Guided breathwork, sound healing, trail runs, and conscious dining curated by bilingual coaches.',
    location: {
      locationType: 'venue',
      address: {
        street: 'Signal Loft Retreat Center',
        city: 'Cape Town',
        state: 'Western Cape',
        zipCode: '8005',
        country: 'South Africa',
      },
    },
    recurrenceRule: 'FREQ=QUARTERLY;BYDAY=FR,SA,SU',
    organizerList: [],
    eventCategoryList: [],
    capacity: 120,
    tags: {focus: ['wellness', 'retreat'], include: ['sound', 'yoga']},
    status: EventStatus.Upcoming,
    lifecycleStatus: EventLifecycleStatus.Published,
    visibility: EventVisibility.Public,
    media: {
      featuredImageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
      otherMediaData: {},
    },
    heroImage: 'https://images.unsplash.com/photo-1441716844725-09cedc13a4e7?auto=format&fit=crop&w=1600&q=80',
    additionalDetails: {wellnessLeads: ['Amina Ngcobo', 'Ethan Mokoena']},
    comments: {},
    privacySetting: EventPrivacySetting.Public,
    orgIndex: 0,
    venueIndex: 0,
  },
  {
    title: 'Streetcar Platform: Transit Stories',
    summary: 'Live art, music, and projections curated on the streetcar platforms of Johannesburg.',
    description:
      'Artists, musicians, and storytellers converge inside a repurposed tram depot to paint motion trails across projected canvases, followed by intimate listening sessions.',
    location: {
      locationType: 'venue',
      address: {
        street: '8 Tramway Ln',
        city: 'Johannesburg',
        state: 'Gauteng',
        zipCode: '2000',
        country: 'South Africa',
      },
    },
    recurrenceRule: 'FREQ=MONTHLY;BYDAY=SA',
    organizerList: [],
    eventCategoryList: [],
    capacity: 220,
    tags: {themes: ['art', 'music'], vibe: ['transit', 'nocturnal'], locale: ['Johannesburg']},
    status: EventStatus.Upcoming,
    lifecycleStatus: EventLifecycleStatus.Published,
    visibility: EventVisibility.Public,
    media: {
      featuredImageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
      otherMediaData: {},
    },
    heroImage: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=80',
    additionalDetails: {curators: ['Nandi Motuba', 'Tumi Thusi'], tram: 'Platform 3'},
    comments: {},
    privacySetting: EventPrivacySetting.Public,
    orgIndex: 3,
    venueIndex: 3,
  },
  {
    title: 'Veld Wellness Immersion',
    summary: 'Three-day reset surrounded by rolling grasses and intentional saunas.',
    description:
      'A small-group retreat that blends sound baths, silent hikes, breathwork, and communal dinners to cultivate calm ahead of the planner-heavy seasons.',
    location: {
      locationType: 'venue',
      address: {
        street: '9 Meadow Ridge',
        city: 'Pretoria',
        state: 'Gauteng',
        zipCode: '0002',
        country: 'South Africa',
      },
    },
    recurrenceRule: 'FREQ=QUARTERLY;BYDAY=FR,SA,SU',
    organizerList: [],
    eventCategoryList: [],
    capacity: 120,
    tags: {focus: ['wellness', 'retreat'], rituals: ['sound', 'campfire'], mood: ['restorative']},
    status: EventStatus.Upcoming,
    lifecycleStatus: EventLifecycleStatus.Published,
    visibility: EventVisibility.Invitation,
    media: {
      featuredImageUrl: 'https://images.unsplash.com/photo-1441716844725-09cedc13a4e7?auto=format&fit=crop&w=1200&q=80',
      otherMediaData: {},
    },
    heroImage: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=80',
    additionalDetails: {lodging: 'Safari tents', meals: 'Farm-to-table harvest'},
    comments: {},
    privacySetting: EventPrivacySetting.Private,
    orgIndex: 4,
    venueIndex: 4,
  },
];

export default events;
