import {CreateEventInputType, EventPrivacySetting, EventStatus} from '@/graphql/types';

const events: CreateEventInputType[] = [
    {
        title: 'Rocking The Daisies 2024',
        description: 'Rocking The Daisies 2024',
        startDate: 'a start date',
        endDate: 'an end date',
        location: 'Cape Town, Winefarm, 8000',
        organizers: ['user002', 'host001'],
        eventCategory: [],
        capacity: 5000,
        rSVPs: [],
        tags: {
            stages: {
                stage1: 'Savanna',
                stage2: 'Heineken',
                stage3: 'Jack Daniels',
            },
            camps: {
                camp1: 'Priority',
                camp2: 'Higher Priority',
            },
        },
        status: EventStatus.Ongoing,
        media: {
            featuredImageUrl: 'https://random.imagecdn.app/500/500',
            otherMediaData: {},
        },
        additionalDetails: {},
        comments: {},
        privacySetting: EventPrivacySetting.Public,
    },
    {
        title: 'Rocking The Daisies 2023',
        description: 'Rocking The Daisies 2023',
        startDate: 'a start date',
        endDate: 'an end date',
        location: 'Cape Town, Stellenbosch, 8000',
        organizers: ['user001', 'host002'],
        eventCategory: [],
        capacity: 5000,
        rSVPs: [],
        tags: {
            stages: {
                stage1: 'Savanna',
                stage2: 'Heineken',
                stage3: 'Jack Daniels',
            },
            camps: {
                camp1: 'Priority',
                camp2: 'Higher Priority',
            },
        },
        status: EventStatus.Completed,
        media: {
            featuredImageUrl: 'https://random.imagecdn.app/400/400',
            otherMediaData: {},
        },
        additionalDetails: {},
        comments: {},
        privacySetting: EventPrivacySetting.Public,
    },
    {
        title: 'coachella 2023',
        description: 'coachella 2023',
        startDate: 'a start date',
        endDate: 'an end date',
        location: 'Cape Town, Stellenbosch, 8000',
        organizers: ['user001', 'host002'],
        eventCategory: [],
        capacity: 5000,
        rSVPs: [],
        tags: {
            stages: {
                stage1: 'Savanna',
                stage2: 'Heineken',
                stage3: 'Jack Daniels',
            },
            camps: {
                camp1: 'Priority',
                camp2: 'Higher Priority',
            },
        },
        status: EventStatus.Completed,
        media: {
            featuredImageUrl: 'https://random.imagecdn.app/550/550',
            otherMediaData: {},
        },
        additionalDetails: {},
        comments: {},
        privacySetting: EventPrivacySetting.Public,
    },
    {
        title: 'Durban July 2023',
        description: 'Durban July 2023',
        startDate: 'a start date',
        endDate: 'an end date',
        location: 'KZN, Durban, 8000',
        organizers: [],
        eventCategory: [],
        capacity: 5000,
        rSVPs: [],
        status: EventStatus.Upcoming,
        media: {
            featuredImageUrl: 'https://random.imagecdn.app/500/550',
            otherMediaData: {},
        },
        additionalDetails: {},
        comments: {},
        privacySetting: EventPrivacySetting.Public,
    },
    {
        title: 'Four Oceans Marathon 2023',
        description: 'Four Oceans Marathon 2023',
        startDate: 'a start date',
        endDate: 'an end date',
        location: 'Cape Town, Winefarm, 8000',
        organizers: ['user002', 'host001'],
        eventCategory: [],
        capacity: 5000,
        rSVPs: [],
        tags: {},
        status: EventStatus.Completed,
        media: {
            featuredImageUrl: 'https://picsum.photos/400',
            otherMediaData: {},
        },
        additionalDetails: {},
        comments: {},
        privacySetting: EventPrivacySetting.Public,
    },
    {
        title: 'The Ring Reloaded Fight Night 2023',
        description: 'The Ring Reloaded Fight Night 2023',
        startDate: 'a start date',
        endDate: 'an end date',
        location: 'Cape Town, Winefarm, 8000',
        organizers: ['user002', 'host001'],
        eventCategory: [],
        capacity: 5000,
        rSVPs: [],
        tags: {},
        status: EventStatus.Completed,
        media: {
            featuredImageUrl: 'https://picsum.photos/300',
            otherMediaData: {},
        },
        additionalDetails: {},
        comments: {},
        privacySetting: EventPrivacySetting.Public,
    },
    {
        title: 'Fear Factor 2023',
        description: 'Fear Factor 2023',
        startDate: 'a start date',
        endDate: 'an end date',
        location: 'Cape Town, Winefarm, 8000',
        organizers: [],
        eventCategory: [],
        capacity: 5000,
        rSVPs: ['user001', 'user002', 'user003'],
        tags: {},
        status: EventStatus.Completed,
        media: {
            featuredImageUrl: 'https://picsum.photos/200',
            otherMediaData: {},
        },
        additionalDetails: {},
        comments: {},
        privacySetting: EventPrivacySetting.Public,
    },
];

export default events;
