import {CreateUserInput} from '@ntlango/commons/types';
import {Gender, SocialVisibility, UserRole} from '@ntlango/commons/types/user';

const users: CreateUserInput[] = [
  {
    // id: 'user001',
    email: 'user001@gmail.com',
    username: 'jackBaur',
    address: {
      country: 'South Africa',
      state: 'KZN',
      city: 'Durban',
      zipCode: '8000',
    },
    interests: [],
    birthdate: '1994-06-26',
    family_name: 'Baur',
    gender: Gender.Male,
    given_name: 'Jack',
    password: 'dfuyihjknbsndhj',
    phone_number: '+12345678990',
    profile_picture: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    bio: 'Trail runner and live music addict based in Durban.',
    primaryTimezone: 'Africa/Johannesburg',
    defaultVisibility: SocialVisibility.Public,
    socialVisibility: SocialVisibility.Public,
    roles: [UserRole.User],
    shareRSVPByDefault: true,
  },
  {
    // id: 'host001',
    email: 'jay@rocknation.com',
    username: 'jayz',
    address: {
      country: 'South Africa',
      state: 'Gauteng',
      city: 'Centurion',
      zipCode: '0600',
    },
    interests: [],
    birthdate: '1990-01-21',
    family_name: 'Carter',
    gender: Gender.Male,
    given_name: 'Sean',
    password: 'tryuik',
    phone_number: '+12345678990',
    profile_picture: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    bio: 'Festival promoter bringing global acts to local stages.',
    primaryTimezone: 'Africa/Johannesburg',
    defaultVisibility: SocialVisibility.Followers,
    socialVisibility: SocialVisibility.Followers,
    roles: [UserRole.Host],
    shareRSVPByDefault: true,
  },
  {
    // id: 'user002',
    email: 'celin@yahoo.com',
    username: 'celin352',
    address: {
      country: 'South Africa',
      state: 'Western Cape',
      city: 'Parklands',
      zipCode: '0901',
    },
    interests: [],
    birthdate: '1999-06-25',
    family_name: 'Maluleke',
    gender: Gender.Female,
    given_name: 'Celin',
    password: 'wreiujk22',
    phone_number: '+12345678990',
    profile_picture: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
    bio: 'Food market explorer and night-run organizer.',
    primaryTimezone: 'Africa/Johannesburg',
    defaultVisibility: SocialVisibility.Public,
    socialVisibility: SocialVisibility.Public,
    roles: [UserRole.User],
    shareRSVPByDefault: true,
  },
  {
    // id: 'host002',
    email: 'Jeff@amazon.com',
    username: 'jeffbez',
    address: {
      country: 'South Africa',
      state: 'Limpopo',
      city: 'Polokwane',
      zipCode: '0800',
    },
    interests: [],
    birthdate: '1997-07-05',
    family_name: 'Bezos',
    gender: Gender.Male,
    given_name: 'Jeff',
    password: '123456789',
    phone_number: '+12345678990',
    profile_picture: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=300&q=80',
    bio: 'Investor by day, rooftop party host by night.',
    primaryTimezone: 'Africa/Johannesburg',
    defaultVisibility: SocialVisibility.Followers,
    socialVisibility: SocialVisibility.Followers,
    roles: [UserRole.Host, UserRole.User],
    shareRSVPByDefault: false,
  },
];

export default users;
