import type {CreateUserInput} from '@ntlango/commons/types';
import {Gender, SocialVisibility, UserRole, FollowPolicy} from '@ntlango/commons/types/user';

const users: CreateUserInput[] = [
  {
    // id: 'user001',
    email: 'user001@gmail.com',
    username: 'jackBaur',
    address: {
      country: 'South Africa',
      state: 'KZN',
      city: 'Durban',
      zipCode: '8000',
    },
    interests: [],
    birthdate: '1994-06-26',
    family_name: 'Baur',
    gender: Gender.Male,
    given_name: 'Jack',
    password: '123456789',
    phone_number: '+12345678990',
    profile_picture: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    bio: 'Trail runner and live music addict based in Durban.',
    primaryTimezone: 'Africa/Johannesburg',
    defaultVisibility: SocialVisibility.Public,
    socialVisibility: SocialVisibility.Public,
    roles: [UserRole.User],
    shareRSVPByDefault: true,
  },
  {
    // id: 'host001',
    email: 'jay@rocknation.com',
    username: 'jayz',
    address: {
      country: 'South Africa',
      state: 'Gauteng',
      city: 'Centurion',
      zipCode: '0600',
    },
    interests: [],
    birthdate: '1990-01-21',
    family_name: 'Carter',
    gender: Gender.Male,
    given_name: 'Sean',
    password: '123456789',
    phone_number: '+12345678990',
    profile_picture: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    bio: 'Festival promoter bringing global acts to local stages.',
    primaryTimezone: 'Africa/Johannesburg',
    defaultVisibility: SocialVisibility.Followers,
    socialVisibility: SocialVisibility.Followers,
    followPolicy: FollowPolicy.RequireApproval,
    roles: [UserRole.Host],
    shareRSVPByDefault: true,
  },
  {
    // id: 'user002',
    email: 'celin@yahoo.com',
    username: 'celin352',
    address: {
      country: 'South Africa',
      state: 'Western Cape',
      city: 'Parklands',
      zipCode: '0901',
    },
    interests: [],
    birthdate: '1999-06-25',
    family_name: 'Maluleke',
    gender: Gender.Female,
    given_name: 'Celin',
    password: '123456789',
    phone_number: '+12345678990',
    profile_picture: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
    bio: 'Food market explorer and night-run organizer.',
    primaryTimezone: 'Africa/Johannesburg',
    defaultVisibility: SocialVisibility.Public,
    socialVisibility: SocialVisibility.Public,
    followPolicy: FollowPolicy.Public,
    roles: [UserRole.User],
    shareRSVPByDefault: true,
  },
  {
    // id: 'host002',
    email: 'Jeff@amazon.com',
    username: 'jeffbez',
    address: {
      country: 'South Africa',
      state: 'Limpopo',
      city: 'Polokwane',
      zipCode: '0800',
    },
    interests: [],
    birthdate: '1997-07-05',
    family_name: 'Bezos',
    gender: Gender.Male,
    given_name: 'Jeff',
    password: '123456789',
    phone_number: '+12345678990',
    profile_picture: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=300&q=80',
    bio: 'Investor by day, rooftop party host by night.',
    primaryTimezone: 'Africa/Johannesburg',
    defaultVisibility: SocialVisibility.Followers,
    socialVisibility: SocialVisibility.Followers,
    followPolicy: FollowPolicy.RequireApproval,
    roles: [UserRole.Host, UserRole.User],
    shareRSVPByDefault: false,
  },
  {
    // id: 'user003',
    email: 'thandi.mvubu@outlook.com',
    username: 'thandimvubu',
    address: {
      country: 'South Africa',
      state: 'Western Cape',
      city: 'Cape Town',
      zipCode: '8001',
    },
    interests: [],
    birthdate: '1995-03-14',
    family_name: 'Mvubu',
    gender: Gender.Female,
    given_name: 'Thandi',
    password: '123456789',
    phone_number: '+27823456789',
    profile_picture: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    bio: 'Yoga instructor and wellness advocate. Love connecting people.',
    primaryTimezone: 'Africa/Johannesburg',
    defaultVisibility: SocialVisibility.Public,
    socialVisibility: SocialVisibility.Public,
    followPolicy: FollowPolicy.Public,
    roles: [UserRole.User],
    shareRSVPByDefault: true,
  },
  {
    // id: 'user004',
    email: 'sipho.ndlovu@gmail.com',
    username: 'sipho_ndlovu',
    address: {
      country: 'South Africa',
      state: 'Gauteng',
      city: 'Johannesburg',
      zipCode: '2001',
    },
    interests: [],
    birthdate: '1992-11-08',
    family_name: 'Ndlovu',
    gender: Gender.Male,
    given_name: 'Sipho',
    password: '123456789',
    phone_number: '+27811234567',
    profile_picture: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    bio: 'Software developer and tech meetup regular.',
    primaryTimezone: 'Africa/Johannesburg',
    defaultVisibility: SocialVisibility.Followers,
    socialVisibility: SocialVisibility.Followers,
    followPolicy: FollowPolicy.Public,
    roles: [UserRole.User],
    shareRSVPByDefault: false,
  },
  {
    // id: 'user005',
    email: 'amara.johnson@live.com',
    username: 'amarajay',
    address: {
      country: 'South Africa',
      state: 'Eastern Cape',
      city: 'Port Elizabeth',
      zipCode: '6001',
    },
    interests: [],
    birthdate: '1998-08-19',
    family_name: 'Johnson',
    gender: Gender.Female,
    given_name: 'Amara',
    password: '123456789',
    phone_number: '+27835551234',
    profile_picture: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=300&q=80',
    bio: 'Photographer capturing urban moments and street culture.',
    primaryTimezone: 'Africa/Johannesburg',
    defaultVisibility: SocialVisibility.Public,
    socialVisibility: SocialVisibility.Public,
    followPolicy: FollowPolicy.RequireApproval,
    roles: [UserRole.User],
    shareRSVPByDefault: true,
  },
];

export default users;
